# Generated by Django 2.2.9 on 2020-01-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='created',
            new_name='added',
        ),
        migrations.AlterField(
            model_name='account',
            name='organization',
            field=models.BooleanField(default=False),
        ),
    ]
