# Generated by Django 2.2.9 on 2020-01-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_auto_20200123_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='managed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='private',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
