# Generated by Django 2.2.9 on 2020-01-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_auto_20200123_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='managed',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
