# Generated by Django 2.2.9 on 2020-01-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_auto_20200123_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('organization', 'name')},
        ),
        migrations.AddField(
            model_name='branch',
            name='last_synced',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='synced',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_history_scaned',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_ongoing_scaned',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
