# Generated by Django 2.2.9 on 2020-01-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_auto_20200123_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='last_scaned_ongoint_commit',
            new_name='last_scaned_ongoing_commit',
        ),
    ]
