# Generated by Django 2.2.9 on 2020-01-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_auto_20200123_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ('repository', 'branch', 'committed')},
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='commited',
            new_name='committed',
        ),
        migrations.AddField(
            model_name='branch',
            name='first_scaned_ongoing_commit',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='github.Commit'),
        ),
        migrations.AddField(
            model_name='commit',
            name='merge',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
