# Generated by Django 2.2.9 on 2020-01-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0008_auto_20200124_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='comments',
            field=models.TextField(editable=False),
        ),
    ]
