# Generated by Django 2.2.9 on 2020-01-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0009_auto_20200124_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leakrule',
            name='exclude_values',
        ),
        migrations.RemoveField(
            model_name='leakrule',
            name='keyword',
        ),
        migrations.AddField(
            model_name='leak',
            name='line_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leakrule',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Database URL')], default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExcludedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('leakrule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclude_values', to='github.LeakRule')),
            ],
        ),
    ]
