# Generated by Django 2.2.9 on 2020-01-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0011_remove_leakrule_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('regex', models.CharField(max_length=256)),
                ('comments', models.CharField(blank=True, max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leakrule',
            name='comments',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
