# Generated by Django 2.2.9 on 2020-01-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0013_leakrule_content_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakrule',
            name='risk_level',
            field=models.SmallIntegerField(choices=[(1, 'Warning'), (2, 'Low Risk'), (3, 'Medium Risk'), (4, 'High Risk')], default=1),
            preserve_default=False,
        ),
    ]
