# Generated by Django 2.2.9 on 2020-01-28 03:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0015_auto_20200128_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='leak',
            name='found',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
