# Generated by Django 2.2.9 on 2020-01-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0016_leak_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excludedfile',
            name='regex',
        ),
        migrations.AddField(
            model_name='excludedfile',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
