# Generated by Django 2.2.9 on 2020-01-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0017_auto_20200128_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leakrule',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Database URL'), (2, 'Env File')]),
        ),
    ]
