# Generated by Django 2.2.9 on 2020-01-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0018_auto_20200129_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excludedvalue',
            old_name='value',
            new_name='regex',
        ),
    ]
