# Generated by Django 2.2.9 on 2020-01-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0019_auto_20200129_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excludedvalue',
            name='regex',
        ),
    ]
