# Generated by Django 2.2.9 on 2020-01-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0020_remove_excludedvalue_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='excludedvalue',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
