# Generated by Django 2.2.9 on 2020-01-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0022_auto_20200129_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='leak',
            name='name',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
