# Generated by Django 2.2.9 on 2020-01-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0023_leak_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leak',
            name='details',
            field=models.CharField(editable=False, max_length=1024),
        ),
    ]
