# Generated by Django 2.2.9 on 2020-01-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0024_auto_20200130_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='history_scan_message',
            field=models.TextField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='history_scan_status',
            field=models.SmallIntegerField(choices=[(1, 'Waiting'), (2, 'Running'), (3, 'Failed')], default=1, editable=False),
        ),
    ]
