# Generated by Django 2.2.9 on 2020-01-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0025_auto_20200130_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_commit',
            field=models.ForeignKey(default=56233, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='github.Commit'),
            preserve_default=False,
        ),
    ]
