# Generated by Django 2.2.9 on 2020-01-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0027_auto_20200130_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_history_scan_end',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_history_scan_start',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
