# Generated by Django 2.2.9 on 2020-01-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0028_auto_20200130_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='history_scan_message',
            field=models.TextField(editable=False, null=True),
        ),
    ]
