# Generated by Django 2.2.9 on 2020-01-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0029_auto_20200131_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leak',
            name='details',
            field=models.TextField(editable=False),
        ),
    ]
