# Generated by Django 2.2.9 on 2020-01-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0030_auto_20200131_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leakrule',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Database URL'), (2, 'Env File'), (3, 'Credential'), (4, 'File')]),
        ),
    ]
