# Generated by Django 2.2.9 on 2020-02-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0032_auto_20200203_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='last_history_scan_end',
            new_name='last_process_end',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='last_history_scan_start',
            new_name='last_process_start',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='history_scan_message',
            new_name='process_message',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='history_scan_status',
            new_name='process_status',
        ),
    ]
