# Generated by Django 2.2.9 on 2020-02-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0033_auto_20200203_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='first_scaned_ongoing_commit',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='last_ongoing_scaned',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='last_scaned_ongoing_commit',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='next_ongoing_commit',
        ),
        migrations.AlterField(
            model_name='repository',
            name='process_status',
            field=models.SmallIntegerField(choices=[(1, 'Waiting'), (2, 'Running'), (2, 'Running'), (3, 'Failed')], default=1, editable=False),
        ),
    ]
