# Generated by Django 2.2.9 on 2020-02-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0036_auto_20200203_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_commit',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='github.Commit'),
        ),
    ]
