# Generated by Django 2.2.9 on 2020-02-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0037_auto_20200203_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='process_status',
            field=models.SmallIntegerField(choices=[(1, 'Waiting'), (2, 'Syncing'), (2, 'Scaning'), (3, 'Failed')], default=1, editable=False),
        ),
        migrations.CreateModel(
            name='ExcludedLeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(editable=False, max_length=512)),
                ('line_number', models.IntegerField(editable=False, null=True)),
                ('name', models.CharField(editable=False, max_length=256, null=True)),
                ('value', models.CharField(editable=False, max_length=1024)),
                ('details', models.TextField(editable=False)),
                ('found', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='github.Branch')),
                ('commit', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='github.Commit')),
                ('excluded_value', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='github.ExcludedValue')),
                ('repository', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='github.Repository')),
                ('rule', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='github.LeakRule')),
            ],
        ),
    ]
