# Generated by Django 2.2.9 on 2020-02-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0038_auto_20200203_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excludedvalue',
            old_name='leakrule',
            new_name='rule',
        ),
        migrations.AddIndex(
            model_name='excludedleak',
            index=models.Index(fields=['rule', 'excluded_value'], name='github_excl_rule_id_5c3291_idx'),
        ),
    ]
