# Generated by Django 2.2.9 on 2020-02-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0039_auto_20200204_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='scaned',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
