# Generated by Django 2.2.9 on 2020-02-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0041_branch_base_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='base_commit',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='github.Commit'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_commit',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='github.Commit'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_scaned_commit',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='github.Commit'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='process_status',
            field=models.SmallIntegerField(choices=[(1, 'Waiting'), (2, 'Syncing'), (3, 'Scaning'), (4, 'Failed')], default=1, editable=False),
        ),
    ]
