# Generated by Django 2.2.9 on 2020-02-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0042_auto_20200204_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='excludedfile',
            name='repositories',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
