# Generated by Django 2.2.9 on 2020-02-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0043_excludedfile_repositories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedvalue',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='github.LeakRule'),
        ),
    ]
