# Generated by Django 2.2.9 on 2020-02-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0044_auto_20200207_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='excludedvalue',
            name='repositories',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
