# Generated by Django 2.2.9 on 2020-02-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0046_auto_20200213_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
